"""
Django settings for rackle project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
from firebase_admin import initialize_app
# import django_heroku
# django_heroku.settings(locals())
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '0o#sy1x(3-_rkn3cx1ub0&eej-30ql3)$c6@7m2@s4ncilm2#f'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = []

DEBUG = True
# TEMPLATE_DEBUG = True
ALLOWED_HOSTS = ["rakle-api.herokuapp.com", "localhost", "127.0.0.1"]
initialize_app()
CORS_ORIGIN_ALLOW_ALL = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'app_login',
    'adminpanel',
    'admin_api',
    'django_filters',
    'knox',
    'drf_yasg',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'knox.auth.TokenAuthentication',
    ],
    'DEFAULT_FILTER_BACKENDS': ('django_filters.rest_framework.DjangoFilterBackend', ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 50
}


SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {

        'KNOX': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    }
}

REST_KNOX = {
    'USER_SERIALIZER': 'app_login.user_serializer.ResiterSerializer',
    # 'TOKEN_TTL': timedelta(minutes=30),
    'TOKEN_TTL': None,

}

ROOT_URLCONF = 'rackle.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR, "template"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rackle.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        #'ENGINE': 'django.db.backends.postgresql_psycopg2',
        #'NAME': "d6jstd64pue4vj",
        #'USER': 'svttobmgfyvosa',
        #'PASSWORD': 'de968b9c2cc44b640de7d757c67d79cc3214913546780d97762fb7c0ab5256c4',
        #'HOST': 'ec2-107-22-238-112.compute-1.amazonaws.com',
        #'PORT': '5432',
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

TIME_ZONE = 'Asia/Kolkata'
DEFAULT_TIME_ZONE = 'Asia/Kolkata'

AUTH_USER_MODEL = 'app_login.UserSignupModel'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

# STATIC_ROOT = 'staticfiles'
# STATIC_URL = '/static/'
# STATIC_ROOT = BASE_DIR / "static"
# STATICFILES_DIRS=[BASE_DIR,'static']
STATIC_URL = '/static/'
STATICFILES_DIRS=[BASE_DIR,'static']
STATIC_ROOT = 'staticfiles'

MEDIA_ROOT =  os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'


razorpay_api_key = "rzp_test_fD7EYc9WMENlIy"
razorpay_api_secret_key = "FxhZsBpQw3vUiSs7Qf7NKBoX"

# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
base_url = 'http://127.0.0.1:8000/api/v1/'
Main_Cat = f'{base_url}main-category/'
# Main_Cat_Post = 'https://rakle-api.herokuapp.com/api/v2/main_cat/create_cat/'

Sub_Cat = 'https://rakle-api.herokuapp.com/api/v2/cat'
main_service = 'https://rakle-api.herokuapp.com/api/v2/main_service'
service = 'https://rakle-api.herokuapp.com/api/v2/service'
best_offer = 'https://rakle-api.herokuapp.com/api/v2/best_offer'
           