# Generated by Django 3.2.10 on 2023-02-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSignupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('age', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=15, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(max_length=500)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('famal', 'Femal'), ('other', 'Other')], default='unknown', max_length=50)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
