# Generated by Django 3.2.10 on 2023-02-04 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0002_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='AllCustomer',
        ),
    ]
