# Generated by Django 4.2.3 on 2023-07-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0002_venderprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcustomer',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
    ]
