# Generated by Django 3.2.10 on 2023-02-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0003_rename_customer_allcustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcustomer',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='allcustomer',
            name='image',
            field=models.ImageField(default='qerdcds', upload_to='customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allcustomer',
            name='name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
