# Generated by Django 4.2.3 on 2023-07-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0006_alter_franchieserprofile_aadhar_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchieserprofile',
            name='no_of_vender',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
