# Generated by Django 3.2.10 on 2023-02-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0006_auto_20230208_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignupmodel',
            name='username',
            field=models.CharField(default=2, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
