# Generated by Django 4.2.3 on 2023-07-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0007_alter_franchieserprofile_no_of_vender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchieserprofile',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
