# Generated by Django 4.2.3 on 2023-07-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0008_alter_franchieserprofile_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignupmodel',
            name='otp',
            field=models.CharField(default='', max_length=30),
        ),
    ]
