# Generated by Django 3.2.10 on 2023-02-11 18:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0001_initial'),
        ('admin_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'default_permissions': ['add', 'change', 'delete', 'view']},
        ),
        migrations.RemoveField(
            model_name='order',
            name='datetime_of_payment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_login.allcustomer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delevery_status',
            field=models.IntegerField(choices=[(1, 'Not Packed'), (2, 'Ready For Shipment'), (3, 'Shipped'), (4, 'Delivered')], default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ref',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='service_quantity',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='time_slot',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='transfer_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OrderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_api.order')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_api.service')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
                ('ref', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('longitude', models.CharField(max_length=50)),
                ('latitude', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=500)),
                ('appartment', models.CharField(max_length=500)),
                ('flat_no', models.CharField(max_length=500)),
                ('save_as', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_login.allcustomer')),
            ],
            options={
                'abstract': False,
                'default_permissions': ['add', 'change', 'delete', 'view'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_api.address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='services',
            field=models.ManyToManyField(through='admin_api.OrderService', to='admin_api.Service'),
        ),
    ]
