# Generated by Django 3.2.10 on 2022-04-02 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0003_bestoffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('rating', models.IntegerField(default=0)),
                ('main_ser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_api.mainservice')),
            ],
        ),
    ]
