# Generated by Django 3.2.10 on 2022-04-02 04:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0004_userreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
