# Generated by Django 3.2.10 on 2022-04-08 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0006_addtocart_productreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
