# Generated by Django 3.2.10 on 2022-05-06 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0007_delete_productreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreview',
            name='main_ser',
        ),
        migrations.AddField(
            model_name='userreview',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_api.service'),
            preserve_default=False,
        ),
    ]
