# Generated by Django 3.2.10 on 2022-05-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0008_auto_20220507_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreview',
            name='city',
        ),
        migrations.AddField(
            model_name='userreview',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userreview',
            name='rating',
            field=models.IntegerField(default=1),
        ),
    ]
