# Generated by Django 4.2.3 on 2023-07-13 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_login', '0003_allcustomer_email'),
        ('admin_api', '0008_auto_20230213_0212'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('oredr_status', models.IntegerField(choices=[(1, 'Accepted'), (2, 'Pending'), (3, 'Rejected')], default=2)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_login.allcustomer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_api.order')),
                ('vender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
