# Generated by Django 4.2.3 on 2023-07-16 02:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0010_alter_orderacceptance_vender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bestoffer',
            old_name='offer',
            new_name='discount',
        ),
        migrations.AddField(
            model_name='bestoffer',
            name='description',
            field=models.TextField(default=datetime.datetime(2023, 7, 16, 2, 43, 24, 943157, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bestoffer',
            name='service',
            field=models.ManyToManyField(to='admin_api.service'),
        ),
        migrations.AddField(
            model_name='bestoffer',
            name='validity',
            field=models.CharField(default=datetime.datetime(2023, 7, 16, 2, 43, 51, 345386, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
