# Generated by Django 4.2.3 on 2023-07-16 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0011_rename_offer_bestoffer_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestoffer',
            name='service',
        ),
        migrations.AddField(
            model_name='bestoffer',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='admin_api.service'),
            preserve_default=False,
        ),
    ]
