# Generated by Django 4.2.3 on 2023-07-16 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0012_remove_bestoffer_service_bestoffer_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='why_service')),
                ('description', models.TextField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_api.service')),
            ],
        ),
    ]
