# Generated by Django 4.2.3 on 2023-07-18 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_api', '0013_whyservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderacceptance',
            name='oredr_status',
            field=models.IntegerField(choices=[(1, 'Accepted'), (2, 'Pending'), (3, 'Rejected'), (4, 'Completed')], default=2),
        ),
        migrations.CreateModel(
            name='VenderWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_api.orderacceptance')),
                ('vender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
