# Generated by Django 3.2.10 on 2023-02-04 17:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_api', '0013_alter_service_service_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addtocart',
            options={'default_permissions': ['add', 'change', 'delete', 'view']},
        ),
        migrations.RemoveField(
            model_name='addtocart',
            name='service_amount',
        ),
        migrations.RemoveField(
            model_name='addtocart',
            name='service_image',
        ),
        migrations.RemoveField(
            model_name='addtocart',
            name='service_name',
        ),
        migrations.AddField(
            model_name='addtocart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addtocart',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='addtocart',
            name='ref',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='addtocart',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='addtocart',
            name='transfer_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 2, 4, 17, 18, 42, 885715, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addtocart',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_login.usersignupmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutservice',
            name='image',
            field=models.ImageField(upload_to='service_about'),
        ),
    ]
